# Generated by Django 2.2 on 2019-04-10 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beachprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='beach',
            unique_together={('beachname', 'safety', 'lat', 'lng')},
        ),
    ]
