# Generated by Django 2.2 on 2019-04-10 05:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beachprofile', '0002_auto_20190410_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='beach',
            name='fav',
            field=models.ManyToManyField(blank=True, related_name='fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
