# Generated by Django 2.2 on 2019-04-10 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beachprofile', '0003_beach_fav'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beach',
            options={'ordering': ['-id']},
        ),
    ]
