# Generated by Django 2.2 on 2019-04-10 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beachprofile', '0004_auto_20190410_0600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beach',
            options={},
        ),
    ]
