# Generated by Django 2.1.7 on 2019-04-11 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beachprofile', '0005_auto_20190410_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('comment', models.CharField(max_length=200)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('beach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beachprofile.Beach')),
                ('user_reviewed', models.ManyToManyField(blank=True, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
