# Generated by Django 2.2 on 2019-04-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachprofile', '0007_auto_20190412_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_reviewed',
        ),
        migrations.AddField(
            model_name='review',
            name='user_reviewed',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
