# Generated by Django 2.2 on 2019-04-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beachprofile', '0008_auto_20190413_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beach',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='beach',
            name='lng',
            field=models.FloatField(),
        ),
    ]
